### ISSUE TITLE
Remove sd when using your own peat characteristics

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/carbonviewer#2]
Minor issse: Since the sd is calculated from the variation in the peat characteristcis database, the function return NA when you are using your own values here. The output could be removed.

**Comment by BenCretois** [comment]
Fixed with [e635b5d](https://github.com/NINAnor/carbonviewer/commit/e635b5dc8a8539ef6cc782ef145282cfa4f6fb18)
