### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by evalieungh** [NINAnor/carbonviewer#3]
Hei!
I was just passing by but noticed you have stated both CC BY-NC-SA 4.0 and MIT license. Those don't match! 

By the way, nice presentation of the software at the NØF conference last week :)

**Comment by BenCretois** [comment]
Thanks for noticing! Fixed with [#9771e75](https://github.com/NINAnor/carbonviewer/commit/9771e75792915d03ca46696e2f7b9e20fba28698)
