### ISSUE TITLE
General suggsestions for improvement

### ISSUE THREAD

**Issue by TrondSimensen** [NINAnor/carbonviewer#4]
Thank you for an excellent app. We tested it in mapping fens in Bykle kommune, Norway, in august 2023. Here are some general suggestions for improvement, based on issues I found confusing when preparing data for the app, and calculating the results.
– It is unclear whether all points with measurements need to be _within_ the polygon of a bog or a fen. It seems that it is possible to include points outside the border of the polygon, it would be nice to specify an advice here.
– In general, the specific requirements for the shp-files need to be better described. It was a bit of trial and error to successfully upload the shp-files. What columns are needed in the attribute table of the shp-file? What shall be the column names in the attribute table? If this is not important, please state so. 
– Does every fen need to be one polygon, or is a mosaic of adjacent polygons with different fen types acceptable? (myrkant, myrflate, etc.). I ended up joining adjacent polygons and dissolving them.
– It is probably described in the paper, but please briefly describe how the volume is calculated. What kind of interpolation techniques are used? 
– It would be good if other coordinate systems than  UTM 32 N, EPSG:25832 were supported. 
– It is not easy to understand what " power " means and to what degree it is essential (we ended up using standard settings). It is stated that it is possible to change the power settings, but it is not easy to understand what it means.
– If relevant, it would be nice to include tons of CO2-equivalents in addition to tons of C.
– Please provide some information about how to interpret the results (especially the meaning of SD in this setting).

**Comment by BenCretois** [comment]
Thanks for the ideas!

I opened an issue with a list of features that could be implemented in the app: https://github.com/NINAnor/carbonviewer/issues/5
